import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header texto={"Header"}></Header>
          <div className="content">
            <div className="vertical-menu">
              <Link href="/dashboard">Dashboard</Link>
              <Link href="/casos">Casos</Link>
              <Link href="/prestadores">Prestadores</Link>
              <Link href="/facturas">Facturas</Link>
            </div>
          </div>
          <div className="main-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
