import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header texto={"Header"}></Header>
        <div className="flex">
          <Sidebar/>
          <div className="main-content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
